### ISSUE TITLE
npm install may have problems

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-bootstrap#184]
I have had two users (@FelFly & @brooksjbr) who have experienced this problem. I am not certain it is a problem with this project though I suspect that it is and would like @TheBlueDog to investigate.

When `npm install`ing a project that uses calcite-bootstrap (ie: [opendata-ui](https://github.com/ArcGIS/opendata-ui)), the npm install fails with errors pointing to permission on calcite-bootstrap. However, they are able to just `npm install esri/calcite-bootstrap#[version]`.

The workaround is to _first_ `npm install esri/calcite-bootstrap#...`, _then_ `npm install`.

In case the above is not clear, the issue is this:

* If they run `npm install` on a project whose package.json references calcite-bootstrap it fails.
* If they run 'npm install esri/calcite-bootstrap#...' it succeeds.

**Comment by TheBlueDog** [comment]
Since this issue was originally created, the repo has been made public, and the public npm is available. Installs of multiple versions has been tested. Closing this issue. If it comes up again, lets create a new issue.
