### ISSUE TITLE
npm installing esri/calcite-bootstrap takes forever

### ISSUE THREAD

**Issue by HeikoH** [Esri/calcite-bootstrap#200]
Adding `esri/calcite-bootstrap` as a dependency to our project causes the build process to take over 2 minutes now instead of 15 secs.

I think it's caused by our build server not having a SSH key for GitHub (it shouldn't need one).

**Comment by HeikoH** [comment]
@TheBlueDog any progress on this?

**Comment by dbouwman** [comment]
@HeikoH are you pulling it in via npm? i.e. `"calcite-bootstrap": "^0.2.6"`

**Comment by HeikoH** [comment]
yes, `npm install --save-dev Esri/calcite-bootstrap#v0.2.51`

**Comment by HeikoH** [comment]
not sure what is going on btw, I thought it had to do with the absence of an SSH key. But after adding one the problem persists. If it helps, I can give you access to a Linux box that has this problem.

**Comment by dbouwman** [comment]
@HeikoH by using `Esri/calcite-bootstrap#vX.Y.Z` that is actually connecting to the github repo vs using the npm CDN.

Can you try deleting that from your local package.json, `rm -rf`-ing the node_modules/calcite-bootstrap folder and then issuing a  `npm i --save-dev calcite-bootstrap`?

Then if that works, it *should* work on your linux box as well.

**Comment by dbouwman** [comment]
@HeikoH also - is your build doing a full pull of all deps on every build? (like Travis CI does)

**Comment by HeikoH** [comment]
ok, that seems to work much better... maybe update install instructions?

> To install Calcite+Bootstrap with npm, type:
> 
> ```
> npm install --save-dev Esri/calcite-bootstrap#v0.2.5
> ```

**Comment by dbouwman** [comment]
@HeikoH - great! I'll close this

@TheBlueDog can you update the docs as per Heiko's note ^^

**Comment by TheBlueDog** [comment]
Will do
