### ISSUE TITLE
Redundant font requests

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-bootstrap#205]
In open data, I see redundant font requests many of which 403.

Calcite bootstrap includes a fast.fonts css file which requests the necessary fonts. These requests are successful because the referrer is the fast.fonts css file which is on the fast.fonts domain. But calcite-bootstrap then also includes specific fonts (the same ones) Those requests fail when our css file is in the s3 bucket because the referrer is the bucket. However, these requests seem to be redundant so we wouldn't want to be making them anyway.

I validated this by going into (in opendata-ui) node_modules/calcite-bootstrap/sass/calcite/\_fonts-avenir.scss and commenting out all the font declarations and leaving only the css file import. The app then made only 4 requests to fastfonts (still too many but that's a different issue) and all were successful. Also, everything _seemed_ to be rendered with the appropriate fonts.

I'm not sure if this change would have undesirable side effects and I'm not sure what the "correct" way to use fastfonts is. But we surely do not want to be making redundant http requests even if they don't 403.

**Comment by alaframboise** [comment]
+1 Apps referencing calcite-bootstrap.css load fast-fonts 4x.

![image](https://cloud.githubusercontent.com/assets/2539681/12676273/99f489b8-c645-11e5-8a4e-70ad899a0746.png)

@TheBlueDog

**Comment by TheBlueDog** [comment]
Issue was fixed in the PR above.

**Comment by bchastain** [comment]
Hey I know this was closed awhile back, but I'm having the same issue in the current version. On Chrome (not FF or IE), I'm getting a lot of fast.fonts.net failures.
![fastfonts](https://cloud.githubusercontent.com/assets/7513579/18277160/13787198-7413-11e6-915f-6a4994eb3c32.png)
