### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by alaframboise** [Esri/calcite-bootstrap#208]
I see cards were added but I don't see them in the gh-pages examples.

https://github.com/Esri/calcite-bootstrap/commit/3d578e0b9592e172744e8a7e865234545ff116c7

**Comment by julio8a** [comment]
Not sure how or when the build takes place, I merged my PR for cards.

**Comment by TheBlueDog** [comment]
There's a first pass of cards in the release. I'd like to enhance the work @julio8a has done and make these more Bootstrap savvy. Currently they are a fixed height and width. Would be nice to have them scalable based on the column width. Maybe the height can be a variable the designer chooses to set or not.

**Comment by TheBlueDog** [comment]
The pages were rebuilt and the cards are shown on the example page:
http://esri.github.io/calcite-bootstrap/examples/#card
