### ISSUE TITLE
Match Calcite-Web Buttons

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-bootstrap#214]
@CassidyB Shouldn't we be consistent with Calcite-Web?  
hover colors on calcite-web get darker. Hover color on Calcite-Bootstrap get lighter.
http://esri.github.io/calcite-web/components/#buttons

CC'd
@kyle-03674 @TheBlueDog @nnblack1980

**Comment by TheBlueDog** [comment]
Agreed, they should match Calcite-Web. Will look into this.
