### ISSUE TITLE
Link to Calcite-maps brings up 404

### ISSUE THREAD

**Issue by skitterm** [Esri/calcite-bootstrap#232]
The link to Calcite Maps at the bottom of the main Calcite Bootstrap page (http://esri.github.io/calcite-bootstrap/) brings up a 404.

**Comment by TheBlueDog** [comment]
Thanks for catching that. I'll get that updated.

Note to self: the new link is http://esri.github.io/calcite-maps/extras/index.html

**Comment by TheBlueDog** [comment]
Issue is fixed and deployed.
