### ISSUE TITLE
Breadcrumb separator isn't encoded

### ISSUE THREAD

**Issue by skitterm** [Esri/calcite-bootstrap#246]
The breadcrumb separator is showing up funny, instead of as a slashed line:

![issue](https://cloud.githubusercontent.com/assets/5875149/14220696/88d1378c-f816-11e5-94c0-e9e633e159ee.JPG)

I repro'd it on my own project as well.

**Comment by TheBlueDog** [comment]
This seems to be a bug in Bootstrap-sass. https://github.com/twbs/bootstrap-sass/issues/919

Upgrading the core might be the fix.

**Comment by TheBlueDog** [comment]
This is fixed in the latest release. It required bumping the bootstrap-sass dependency to 0.3.6.
