### ISSUE TITLE
Question: Does Calcite-bootstrap extend the bootstrap JavaScript?

### ISSUE THREAD

**Issue by skitterm** [Esri/calcite-bootstrap#266]
I'm looking at using <a href="https://react-bootstrap.github.io/getting-started.html">React-Bootstrap</a>, but one of its stipulations is that it doesn't play well with libraries that extend Bootstrap's JS functionality. Does Calcite Bootstrap use the bootstrap JS out-of-the-box, or is some of it extended? Are there plans to extend it?

**Comment by TheBlueDog** [comment]
Calcite Bootstrap uses the core unmodified Bootstrap JB library. There are no plans to change from that.
