### ISSUE TITLE
Broken link on web site

### ISSUE THREAD

**Issue by eleanorh** [Esri/calcite-bootstrap#274]
http://esri.github.io/calcite-bootstrap/#builtwithcb

![image](https://cloud.githubusercontent.com/assets/3044334/16348218/17653896-3a06-11e6-9caf-d8a75a458d96.png)

Looks like link should be http://esri.github.io/calcite-maps/samples/index.html

**Comment by TheBlueDog** [comment]
Just deployed the update for gh-pages. The link has been fixed. Thanks @eleanorh
