### ISSUE TITLE
variable name typos

### ISSUE THREAD

**Issue by asizer** [Esri/calcite-bootstrap#276]
In the _variables.scss file, there are two vars with dashes that should be underscores:

https://github.com/Esri/calcite-bootstrap/blob/master/lib/sass/calcite/_variables.scss#L39
https://github.com/Esri/calcite-bootstrap/blob/master/lib/sass/calcite/_variables.scss#L144

**Comment by TheBlueDog** [comment]
Geez. Good catch @asizer! Thanks for the help.
