### ISSUE TITLE
Pages empty or 404s

### ISSUE THREAD

**Issue by GeraintBundy** [Esri/calcite-bootstrap#280]
All the pages on http://esri.github.io/calcite-bootstrap/ are either empty or 404s.

**Comment by GeraintBundy** [comment]
All the pages on http://esri.github.io/calcite-bootstrap/ are either empty or 404s.

**Comment by Cezus** [comment]
At the moment the issue that is mentioned above is still present. What is the status of this project? What is the roadmap? We first have seen [Boostrap-map](https://github.com/Esri/bootstrap-map-js), then [calcite-maps](https://github.com/Esri/calcite-maps) and now [calcite-bootstrap](https://github.com/Esri/calcite-bootstrap). 

It looks like also this project has been halted (check the frequency before the last release (version 0.3.3)).

The strange thing is, calcite theme is as beta integrated in version 3.16 of the ArcGIS for JavaScript API. In the "What's new" of version 3.17 nothing is mentioned about calcite theme. So for my view, the only handhold that calcite is **not** halted is the integration from 3.16 of the JavaScript API

**Comment by dbouwman** [comment]
Apologies, the Components content does not exist. That said, the Open Data team, (main consumers of calcite-bootstrap) rely on the Bootstrap documentation (http://getbootstrap.com/) as `calcite-bootstrap` is simply a "Calcite" theme applied to bootstrap itself. 

We are also planning to re-work this entire project so it's a "bootstrap theme" vs a custom build of bootstrap... timeframe TBD, but definitely in 2017
