### ISSUE TITLE
broken link for "Navbars" on the documentation page

### ISSUE THREAD

**Issue by ez4gis** [Esri/calcite-bootstrap#305]
Reporting A minor issue with documentation [landing page](https://esri.github.io/calcite-bootstrap/index.html).  On the page, the "Navbars" link in the left panel points to https://esri.github.io/calcite-bootstrap/index.html#navbar.  However clicking on it doesn't load or scroll to the right section.

**Comment by jgravois** [comment]
good catch. thx!
